
import java.util.Date;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Grade extends javax.swing.JFrame {

    /**
     * Creates new form Grade
     */
    public Grade() {
        initComponents();
    }
// place this inside your form class, not inside another method
    //this is where the conditions are checked
private String getGrade(String input) {
    if (input == null) return "Invalid";
    input = input.trim();
    if (input.isEmpty()) return "Invalid";

    try {
        int score = Integer.parseInt(input); // will throw if not digits

        if (score >= 80 && score <= 100) return "A";
        if (score >= 70 && score < 80)  return "B";
        if (score >= 60 && score < 70)  return "C";
        if (score >= 50 && score < 60)  return "D";
        if (score >= 0  && score < 50)  return "F";

        return "Out of Range";
    } catch (NumberFormatException e) {
        return "Invalid";
    }
}

// --- New Method for Overall Grade Name ---
private String getOverallGradeName(double averageScore) {
    
    // Round the average to the nearest whole number for clear comparison
    int score = (int) Math.round(averageScore);

    // Use percentage average for overall grade names
    if (score >= 90) { 
        return " Presec-Legon ";
    }
    if (score >= 80) {
        return " Prempeh College";
    }
    if (score >= 70) {
        return " St. Peter's ";
    }
    if (score >= 60) {
        return " Accra Academy ";
    }
    if (score >= 50) {
        return " Self Placement";
    }
    
    // If the average is below 50 (total < 300)
    if (score >= 0) {
        return " Fail";
    }
    
    return " N/A";
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maths = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        ave = new javax.swing.JTextField();
        gra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ict = new javax.swing.JTextField();
        english = new javax.swing.JTextField();
        soc = new javax.swing.JTextField();
        secience = new javax.swing.JTextField();
        tech = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        index = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("MATHEMATICS: ");

        jLabel5.setText("ENGLISH LANGUAGE:");

        jLabel6.setText("INTERGRATED SECIENCE: ");

        jLabel7.setText("ICT:");

        jLabel8.setText("SOCIAL STUDIES: ");

        jLabel9.setText("CAREER TECHNOLOGY: ");

        maths.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        maths.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        maths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsActionPerformed(evt);
            }
        });
        maths.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mathsKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AVERAGE:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SCHOOL:");

        total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        total.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        ave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));
        ave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aveActionPerformed(evt);
            }
        });

        gra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gra.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Generate ");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 204, 255), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 204, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Print");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gra, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ave, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jButton3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        ict.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ict.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        ict.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ictKeyTyped(evt);
            }
        });

        english.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        english.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        english.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                englishKeyTyped(evt);
            }
        });

        soc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        soc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        soc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                socKeyTyped(evt);
            }
        });

        secience.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        secience.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        secience.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secienceKeyTyped(evt);
            }
        });

        tech.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tech.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        tech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                techKeyTyped(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("RS GRADE CHECKER ONLINE SYSTEM ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Your  most comprehensive Grade checker online. Make sure you input the correct information");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Input your marks to have your Total,Average and Grade display");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(194, 194, 194))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel10.setText("CANDATE NAME: ");

        jLabel11.setText("INDEX NUMBER:");

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        index.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        index.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexActionPerformed(evt);
            }
        });
        index.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                indexKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maths, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ict, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secience, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tech, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(index)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(secience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(soc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(tech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(987, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                       
    // --- 1. DECLARE AND INITIALIZE ALL CALCULATION VARIABLES FIRST ---
    int totalSum = 0;       
    double average = 0.0;    // <--- Must be a double for the average
    String finalGrade = " N/A";
    
    // Initializing the individual scores 
    int socScore = 0;
    int mathsScore = 0;
    int englishScore = 0;
    int ictScore = 0;
    int scienceScore = 0; 
    int techScore = 0;
    
    int numberOfSubjects = 6;
    
    
    

    // --- Validate index number: must be exactly 10 digits ---
    String idx = index.getText().trim();
    if (!idx.matches("\\d{10}")) {
        JOptionPane.showMessageDialog(null, "Invalid Index number (must be exactly 10 digits).");
        return;
    }
// --- Initial Header Setup for JTextArea ('result') ---
    result.setText("                                       ************************************ \n");
    result.append("                                          RS ONLINE GRADE CHECKER \n");
    result.append("                                        ******************************** \n");
    
    // --- Compute individual subject grades and validate input ---
    String mathsGrade   = getGrade(maths.getText());
    String englishGrade = getGrade(english.getText());
    String scienceGrade = getGrade(secience.getText()); 
    String ictGrade     = getGrade(ict.getText());
    String socGrade     = getGrade(soc.getText()); // Social Studies grade calculation
    String techGrade    = getGrade(tech.getText());

    // --- If any subject input is invalid, show error and stop ---
    if (mathsGrade.equals("Invalid") ||
        englishGrade.equals("Invalid") ||
        scienceGrade.equals("Invalid") ||
        ictGrade.equals("Invalid") ||
        socGrade.equals("Invalid") ||
        techGrade.equals("Invalid")) {

        result.setText("ERROR: One or more subjects contain invalid input.\nPlease enter numeric scores (0-100) for all subjects.");
        
        // Clear summary fields on error
        total.setText(" N/A");
        ave.setText(" N/A");
        gra.setText(" N/A");
        return;
    }


    try {
        // --- 2. PARSE SCORES AND CALCULATE TOTAL & AVERAGE ---
        // 1. Convert text to integers
        socScore = Integer.parseInt(soc.getText());
        mathsScore = Integer.parseInt(maths.getText());
        englishScore = Integer.parseInt(english.getText());
        ictScore = Integer.parseInt(ict.getText());
        techScore = Integer.parseInt(tech.getText());
        scienceScore = Integer.parseInt(secience.getText()); // Use 'secience'
        
        // 2. Calculate the total sum (Must be done before average)
        totalSum = socScore + mathsScore + englishScore + ictScore + techScore + scienceScore;

        // 3. Calculate the average (FIXED: Uses type casting to solve the "0" issue)
        average = (double) totalSum / numberOfSubjects;
        
        // 4. Calculate the Final Overall Grade Name
        finalGrade = getOverallGradeName(average); 

    } catch (NumberFormatException e) {
        // Fallback catch block (should be rarely reached due to early validation)
        JOptionPane.showMessageDialog(null, "A critical parsing error occurred.", "System Error", JOptionPane.ERROR_MESSAGE);
        
        // Set output fields to error state
        total.setText(" N/A");
        ave.setText(" N/A");
        gra.setText(" N/A");
        return;
    }
    
    // --------------------------------------------------------------------------------
    // 3. DISPLAY RESULTS & BUILD FINAL REPORT (AFTER TRY/CATCH)
    // --------------------------------------------------------------------------------

    // Update the output JTextFields (Displaying the Total, Average, and Grade Name)
    total.setText(String.valueOf(totalSum));
    ave.setText(String.format("%.2f", average)); 
    gra.setText(finalGrade); // Displays the overall grade name (e.g., "Distinction")

    // Build the final result JTextArea report
    Date now = new Date();
    StringBuilder sb = new StringBuilder();

    sb.append("DATE: ").append(now.toString()).append("\n\n");
    sb.append("CANDIDATE NAME: ").append(name.getText()).append("\n\n");
    sb.append("CANDIDATE NUMBER: ").append(idx).append("\n\n");
    sb.append("************************************** \n\n");
    
    // Individual Subject Grades
    sb.append("MATHEMATICS GRADE: ").append(mathsGrade).append("\n");
    sb.append("ENGLISH LANGUAGE GRADE: ").append(englishGrade).append("\n");
    sb.append("INTEGRATED SCIENCE GRADE: ").append(scienceGrade).append("\n");
    sb.append("ICT GRADE: ").append(ictGrade).append("\n");
    sb.append("SOCIAL STUDIES GRADE: ").append(socGrade).append("\n"); 
    sb.append("CAREER TECHNOLOGY GRADE: ").append(techGrade).append("\n\n");
    
    sb.append("************************************************************************** \n");
    
    // Final Summary
    sb.append("\n TOTAL MARK: ").append(totalSum).append("\n");
    sb.append("AVERAGE MARK: ").append(ave.getText()).append("\n");
    sb.append("SCHOOL PLACED: ").append(gra.getText()).append("\n");
    
    // Append the newly generated summary to the header text already in the JTextArea
    result.append(sb.toString()); 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void indexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexActionPerformed
         
    }//GEN-LAST:event_indexActionPerformed

    private void mathsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathsKeyTyped
         char c =evt.getKeyChar();
     if(!Character.isDigit(c)){
         evt.consume();   //this will block all letters and symbols, from entery into the maths section
     }
    }//GEN-LAST:event_mathsKeyTyped

    private void englishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_englishKeyTyped
         char c =evt.getKeyChar();
     if(!Character.isDigit(c)){
         evt.consume();   //this will block all letters and symbols, from entery into the english section
     }
    }//GEN-LAST:event_englishKeyTyped

    private void secienceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secienceKeyTyped
         char c =evt.getKeyChar();
     if(!Character.isDigit(c)){
         evt.consume();   //this will block all letters and symbols, from entery into the secince section
     }
    }//GEN-LAST:event_secienceKeyTyped

    private void ictKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ictKeyTyped
         char c =evt.getKeyChar();
     if(!Character.isDigit(c)){
         evt.consume();   //this will block all letters and symbols, from entery into the ict section
     }
    }//GEN-LAST:event_ictKeyTyped

    private void socKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_socKeyTyped
         char c =evt.getKeyChar();
     if(!Character.isDigit(c)){
         evt.consume();   //this will block all letters and symbols, from entery into the soc section
     }
    }//GEN-LAST:event_socKeyTyped

    private void techKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_techKeyTyped
        char c =evt.getKeyChar();
     if(!Character.isDigit(c)){
         evt.consume();   //this will block all letters and symbols, from entery into the tech section
     }
    }//GEN-LAST:event_techKeyTyped

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
         char c =evt.getKeyChar();
     if(!Character.isLetter(c) && c != ' '){ //without && c ! = ' ' it will also not allow space 
         evt.consume();   //this is for only the name part and no digit wil be allowed
     }
    }//GEN-LAST:event_nameKeyTyped

    private void indexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indexKeyTyped
         char c =evt.getKeyChar();
     if(!Character.isDigit(c)){
         evt.consume();   //this will block all letters and symbols, from entery into the index section
     }
    }//GEN-LAST:event_indexKeyTyped

    private void mathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsActionPerformed
     
    }//GEN-LAST:event_mathsActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
       
        
    }//GEN-LAST:event_totalActionPerformed

    private void aveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // To reset:
        name.setText(" ");
        index.setText(" ");
        ict.setText(" ");
        soc.setText(" ");
        tech.setText(" ");
        maths.setText(" ");
        english.setText(" ");
        gra.setText(" ");
        total.setText(" ");
        ave.setText(" ");
        secience.setText(" ");
        result.setText(" ");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
      result.print();   //this is for the print buttom
  }
  catch(Exception e)
    {
      
  }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ave;
    private javax.swing.JTextField english;
    private javax.swing.JTextField gra;
    private javax.swing.JTextField ict;
    private javax.swing.JTextField index;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maths;
    private javax.swing.JTextField name;
    private javax.swing.JTextArea result;
    private javax.swing.JTextField secience;
    private javax.swing.JTextField soc;
    private javax.swing.JTextField tech;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
